### ISSUE TITLE
 没系统设计，显然还不够卷

### ISSUE THREAD

**Issue by MoeYang** [xiaowei520/go_interview#26]
我来出两题遇到的：
1、抢红包
2、微信朋友圈的time-line和红点通知

**Comment by xiaowei520** [comment]
https://github.com/go-share-team/go_interview/blob/master/%E9%9D%A2%E7%BB%8F/%E5%85%B6%E4%BB%96/Go-5%E5%B9%B4%E7%A4%BE%E6%8B%9B-202003.md   里面是有朋友圈设计的。抢红包 微信群讨论过。

**Comment by xiaowei520** [comment]
> https://github.com/go-share-team/go_interview/blob/master/%E9%9D%A2%E7%BB%8F/%E5%85%B6%E4%BB%96/Go-5%E5%B9%B4%E7%A4%BE%E6%8B%9B-202003.md 里面是有朋友圈设计的。抢红包 微信群讨论过。
